name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
            
        - name: List files
          run: ls -ltra

        - name: Executing shell script
          run: |
                chmod +x .github/workflows/ascii-shell.sh
                .github/workflows/ascii-shell.sh